.env.local
README.md
build-custom-images.sh
packages/client-registry-opencr/Dockerfile

Updates to local build steps/configuration

---

packages/client-registry-opencr/Dockerfile

Instead of manually building the base image.
An updated Docker image has been released which contains the fixed we needed. We no longer have to manually build the OpenCR images from their m,ain repo, and instead can make use fo the latest published docker image
Resolves #
-
-
-

Set latest OpenCR base image

---

packages/shared-health-record/docker-compose.dev.yml

This PR fixes SHR mediator published port 3000 conflicting with Grafana

fix: shr port conflicting with grafana

---

config.yaml

Update config.yaml : duplicate profiles

---

.env.qa
config.yaml
packages/reverse-proxy-nginx/package-conf-insecure/http-opencr-insecure.conf
packages/reverse-proxy-nginx/package-conf-secure/http-opencr-secure.conf
packages/reverse-proxy-nginx/package-metadata.json
packages/reverse-proxy-nginx/swarm.sh

This PR adds nginx + ssl capability for QA env

feat: nginx + ssl for QA

---

packages/shared-health-record/docker-compose.dev.yml
packages/shared-health-record/docker-compose.yml

Define exposed SHR port in dev setup

---

projects/shr-mediator/.eslintrc.js
projects/shr-mediator/.gitignore
projects/shr-mediator/.prettierrc
projects/shr-mediator/README.md
projects/shr-mediator/nest-cli.json
projects/shr-mediator/package-lock.json
projects/shr-mediator/package.json
projects/shr-mediator/src/app-settings.json
projects/shr-mediator/src/app.controller.spec.ts
projects/shr-mediator/src/app.controller.ts
projects/shr-mediator/src/app.module.ts
projects/shr-mediator/src/app.service.ts
projects/shr-mediator/src/botswana/botswana.module.ts
projects/shr-mediator/src/common/common.module.ts
projects/shr-mediator/src/common/controllers/common.controller.spec.ts
projects/shr-mediator/src/common/controllers/common.controller.ts
projects/shr-mediator/src/common/services/common.service.spec.ts
projects/shr-mediator/src/common/services/common.service.ts
projects/shr-mediator/src/config/index.ts
projects/shr-mediator/src/main.ts
projects/shr-mediator/src/openhim/openhim.module.ts
projects/shr-mediator/src/openhim/openhim.service.ts
projects/shr-mediator/src/openhim/types.ts
projects/shr-mediator/test/app.e2e-spec.ts
projects/shr-mediator/test/jest-e2e.json
projects/shr-mediator/tsconfig.build.json
projects/shr-mediator/tsconfig.json

This PR adds the SHR mediator project (new version of the shared health record) using NestJS

feat: add boilerplate for shr mediator new version

---

projects/omang-service-mediator/src/modules/mpi/services/mpi.service.ts
projects/omang-service-mediator/src/modules/patient/controllers/patient.controller.ts

The following PR adds an endpoint proxies incoming requests to OpenCR to create a patient record. This is a temporary measure until OpenCR fixes the issue of returning an array of outcomes instead of the patient resource being submitted.
See issue : https://github.com/intrahealth/client-registry/issues/147
Resolves #
-
-
-

fix: opencr passthrough for patient creation

---

packages/interoperability-layer-openhim/importer/volume/openhim-import.json

Update OpenHIM initial config.
Resolves #
-
-
-

feat: update openhim initial config

---

packages/interoperability-layer-openhim/importer/volume/openhim-import.json

fix: reset openhim config

---

projects/shr-mediator/src/botswana/controllers/lab.controller.ts

This PR fixes lab order bundle response handling.
Resolves #
-
-
-

fix: handle bundle response for lab workflow

---

projects/shr-mediator/src/botswana/services/hl7.service.ts

This PR handles oru duplicates issues.

fix: handle oru duplicates

---

packages/shr-mediator/package-metadata.json
projects/shr-mediator/src/botswana/controllers/kafka-consumer.controller.ts
projects/shr-mediator/src/botswana/controllers/lab.controller.ts
projects/shr-mediator/src/botswana/services/terminology.service.spec.ts
projects/shr-mediator/src/botswana/services/terminology.service.ts

This PR we translate concepts before pushing to Kafka to make it easy for EMR systems to recognize errors in lab codes (ServiceRequest coding)

fix: move concept translation on submit

---

projects/shr-mediator/src/botswana/services/ipms.service.ts
projects/shr-mediator/src/botswana/services/terminology.service.ts
projects/shr-mediator/src/config/index.ts

This PR handles multiple test results properly

fix: handle multiple test results (ORU)

---

.env.local
projects/shr-mediator/src/botswana/controllers/lab.controller.ts

Update the content type for fhir passthrough lab/metadata endpoint

---

projects/openhim-mediator-fhir-converter/src/lib/handlebars-converter/handlebars-helpers.js

fix: fhir hl7 converter

---

.env.uat
config.yaml

Added profile for UAT

---

projects/shr-mediator/src/common/controllers/fhir.controller.ts

Updates the fhir resource endpoint content type

---

.env.local

Cleanup of the env.local file to original state

---

projects/shr-mediator/src/botswana/services/lab-workflow.service.ts

Resolves # https://app.clickup.com/t/86c0wnn0f
-
-
-

Allows validation of PIMS bundle

---

packages/interoperability-layer-openhim/initiate-replica-set.sh

Adds iniate-replica-set script file

---

projects/omang-service-mediator/Dockerfile
projects/omang-service-mediator/src/config/ormconfig.ts
projects/omang-service-mediator/src/modules/immigration/repositories/immigration-repository.ts

This PR adds support for old legacy Oracle databases, v10 and v11, on which BDRS and Immigrations registries run on. We have added Oracle Instant Client installation on the Omang service mediator Dockerfile to achieve this since it is required for connection to those older versions of Oracle. 
The PR also fixes some typo issues identified on the mediator project.
Resolves [#86c0wnp4x](https://app.clickup.com/t/9015459008/86c0wnp4x)
-
-
-

Fix Omang Mediator to Allow for Legacy Oracle Database Connections

---

.env.qa

Resolves [#86c2gzc11](https://app.clickup.com/t/86c2gzc11)
-
-
-

fix env.qa variables

---

.env.pilot
projects/omang-service-mediator/Dockerfile

Updated code to handle changes in pilot environment

---

.env.prod
.env.qa
.env.uat

Adds MLLP env variables to Prod uat env files

---

.env.local
.env.prod
.env.qa
.env.uat
packages/interoperability-layer-openhim/importer/volume/openhim-import.json
packages/interoperability-layer-openhim/package-metadata.json

Resolves # 
https://app.clickup.com/t/86c317dp1
-
-
-

Add default clients for PIMS and OpenMRS on OpenHIM(bemr-client/pims-client)
